# Generated by Django 2.0.5 on 2018-05-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('visited_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('robots_txt', models.TextField(blank=True, default=None, null=True)),
                ('robots_txt_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=5000)),
                ('url_sha256', models.CharField(max_length=64, unique=True)),
                ('visited_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='django_webcrawler.Domain')),
                ('links_to', models.ManyToManyField(related_name='linked_from', to='django_webcrawler.Url')),
            ],
        ),
    ]
